CREATE USER DB_REPL_USER REPLICATION LOGIN ENCRYPTED PASSWORD 'DB_REPL_PASSWORD';

CREATE DATABASE DB_DATABASE;

\c DB_DATABASE;

CREATE TABLE IF NOT EXISTS emails (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS numbers (
    id SERIAL PRIMARY KEY,
    number VARCHAR(255)
);


GRANT SELECT ON ALL TABLES IN SCHEMA public TO DB_REPL_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT ON TABLES TO DB_REPL_USER;
